### ISSUE TITLE
Feature Requests: typing interpolated variable to json serialisation and csvDataset default filepath

### ISSUE THREAD

**Issue by MaksSieve** [abstracta/jmeter-java-dsl#104]
I've found this problem in graphqlSqmpler, but I think all HttpSamplers have it.

Use case:
```java
csvDataset("some_file"),
graphqlSampler("some_name", "https://some_url", "query some_query")
  .variable("var_name", "${var_value_from_csv}")
```

The problem is that in this case variable will passed to final http body strictly as a string, but normally there could be numbers.

Another point is that csvDataset needs absolute path to configure, in my view the common case should be using `src/test/resource` path for all test resources (data sets, graphql schemas and queries etc.). 

So, my proposals are:

* add typing to `variable()` method, i.e. in this style `variable("var_name", "${var_value}", Integer::class)`, with String type as default.
* set default behaviour of csvDataset to use `src/test/resource`, and if there isn't requested file than use passed path as absolute

**Comment by rabelenda** [comment]
Hello, thank you for reporting this!

Small tip/advice: for the future consider creating separate issues so is easier to track and discuss each topic.

Regarding `grapqlSampler.variable` method:
* is nice that you identified such issue, thank you for this. 
* remember that for complex scenarios you can use `variables` method which receives the raw Json string (now that I see it I think we should rename it as `variablesJson`). 
* In any case I think your proposal makes sense. I wonder though, if we can further simplify it. 
What about something like `.rawVariable("var_name", "${var_value}")`? do you think it is intuitive? 
with such method we could provide any complex structure and no need to specify type would be needed.

About csvDataset, and other cases like the one we previously discussed [here](https://github.com/abstracta/jmeter-java-dsl/issues/85#issuecomment-1093315988):
* Although I think it would be nice to encourage good practice of hosting resources in `src/test/resources` for maven projects and reduce boiler plate code as much as possible, assuming that "some_file" is a file in `src/test/resources` is misleading in general java programming. 
* You have to take into consideration that in some projects tests might be in maven project under `src/test/resources`, but in general, in java programming, when you specify a relative file path, the path is relative to the working directory of the application (which depends where you run the code). 
* Additionally, `src/test/resources` is a maven specific directory, but you may have files in other dirs (for example when using gradle and not using maven structure, or even other directory structures & build tools).
* Furthermore, would be nice to be consistent when specifying files in general in the API. For instance, doesn't make sense for jtlWriter() to specify a path to a resource.
* So far, I think providing a `csvDataset(new TestResource("/myFile"))` option is a good trade off, providing explicit syntax that is easily recognizable and understandable and is generic enough (since is not limited to `src/test/resources` and just uses java general naming convention for resources) with the downside of requiring some additional verbosity.
* Do you have any other ideas? Or comments on what I described above?

Thank you again for reporting this, and proposing improvements and alternatives to existing API. We are always looking for new ways to improving it and reviewing decisions.

Regards

**Comment by MaksSieve** [comment]
Thanks for critical review!

* About graphqlSampler, I think adding .jsonVariables() and .rawVariabe() will solve problems, it remains only to implement it :)
* Regarding the second question, I am a technazi myself and I think we should guide our users with a firm hand to a brighter future 😁 , but seriously I agree with the way where we use TestResource class, but maybe we may add DSL-method testResource(String path) with class construction inside to preserve consistency of DSL itself.

**Comment by rabelenda** [comment]
We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.54) which includes both features. 

I hope it fits your needs.

Regards
