### ISSUE TITLE
RPS thread group initial RPS bug

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#106]
initial RPS always setting to 1. Seems really bad.

This 

  `.rampToAndHold(0.003, Duration.ofSeconds(30), Duration.ofMinutes(3))`

converts to this

![a082c0add0f491cecee8bec1916891599eaa2c99a335378313abc158803554db_0.png](https://user-images.githubusercontent.com/9977326/164537388-488a7920-624e-48b5-bdeb-7cad53f530a1.png)

but i trying to increase the load

**Comment by kirillyu** [comment]
We need the setter i think

**Comment by rabelenda** [comment]
Have you tried something like:

```java
.rampTo(X, Duration.ZERO) 
```

Please, be aware of the issue we warn [here](https://abstracta.github.io/jmeter-java-dsl/guide/#throughput-based-thread-group) about low rps values.

**Comment by kirillyu** [comment]
Low rps works not ideal, but normal with enough thread pool. When one is stuck another one can operate.

**Comment by rabelenda** [comment]
Sorry, I didn't saw your second comment before answering :).

Regarding low rps and thread pool, and threads stuck: in the scenario you depicted with default rpsThreadGroup config, don't you experience the thread being stuck for 1/0.003=5.5 minutes? Which wouldn't be desirable I guess since you wanted to have that phase only for 3 mins. Same, or worst thing would happen if you use more initial threads, because you will generate more rps in first iteration and throughputShapingTimer will calculate a further sleep time, which will make all threads to block (you would experience kind of small bursts of requests).

Regarding providing a method like `.initialRps(X)`, we could do it and sounds like a good idea to avoid the "workaround" of using `.rampTo(X, Duration.ZERO)`.

**Comment by kirillyu** [comment]
Looked at this issue - no need to get initial Rps because we insert a high rps sampler anyway when rps is low to achieve good accuracy

**Comment by kirillyu** [comment]
Seems that we really need open model)
