### ISSUE TITLE
The older versions showing up as the latest in maven central/IntelliJ

### ISSUE THREAD

**Issue by QAInsights** [abstracta/jmeter-java-dsl#110]
The older version of JMeter DSL is showing as the latest. Could you please check the issue? Please see the below screenshots.

![image](https://user-images.githubusercontent.com/2826376/165417405-31cb9f6d-d607-4344-9b23-e48f68919cd5.png)

![image](https://user-images.githubusercontent.com/2826376/165417431-8c4c3a65-36fb-43c6-a792-e3d4a7e94482.png)

**Comment by rabelenda** [comment]
Hello @QAInsights , nice to see you around :).

Thank you for brining this! 

This is a known issue due to a mistake when we tried to do a release (we missed a dot). Sadly, we can't remove the version from maven repository, [here](https://issues.sonatype.org/browse/MVNCENTRAL-7052) is our request and as much we got was the removal of the jar, so, if anyone tries to use that version, it will fail.

The only way I see to overcome this issue right now is to change jmeter dsl coordinates (change maven group id or artifact id). We have plans to do at near/medium term a major release (1.0) and when we do that we will probably change artifacts coordinates (to fix this issue at the same time), but, meanwhile, I don't think is worth changing it before such release due to the level of impact of changing coordinates vs leaving current issue.

Does anyone have other ideas?

Regards

**Comment by QAInsights** [comment]
Thanks, @rabelenda :) I understand. I can wait for 1.0. Is it possible to highlight this somewhere in the docs? It would be helpful for newbies like me.

**Comment by kirillyu** [comment]
maybe we can to release 1.0 and probably it should fix it?

**Comment by rabelenda** [comment]
Before doing release 1.0 we want to review API compatibility with some changes we plan to do in the near future, and would like to avoid releasing 1.0 to soon after having to release 2.0. We will keep this issue open until we fix this, and hope to have a fix/release soon.

**Comment by rabelenda** [comment]
Today we released 1.0, so this should no longer be an issue.
