### ISSUE TITLE
HTTP Sampler with Proxy

### ISSUE THREAD

**Issue by QAInsights** [abstracta/jmeter-java-dsl#112]
Is it possible to run the DSL code via Proxy. The use case is to capture the request/response via Fiddler like tools. 

I tried `jmx2dsl`, it is not generating the proxy configuration.

**Comment by rabelenda** [comment]
Hello,

Thanks to bring this into attention. Is something that we had in the radar for some time but since no one has requested it we haven't prioritized it. Now we will :).

Currently, there is no way to set a proxy unless you extend current DslHttpSampler, DslHttpDefaults or use wrappers which are not as handy/simple. We will implement simple support for this, stay tuned.

We will also add the conversion for jmx2dsl for this feature.

Regards

**Comment by rabelenda** [comment]
We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.55) which allows configuring the proxy.

Please let us know if this works for you.

Regards
