### ISSUE TITLE
DSL to understand ${P__(THREADS,1)} in Thread Group

### ISSUE THREAD

**Issue by QAInsights** [abstracta/jmeter-java-dsl#113]
Can we have the feature to understand the Thread Group configuration as parameterized variabled e.g.  `${P__(THREADS,1)}`?

Right now, it is throwing the below error:

```
DSL does currently only support numeric values for ThreadGroup.num_threads, but found: ${__P(THREADS,1)}
```

**Comment by rabelenda** [comment]
Hello, thank you again for bringing these questions and requests!

From the message you post I see that seems you are trying to use `jmx2dsl` to convert an existing test plan. Would be interesting yo know how are you using such test plan, and what would be the expected DSL from your stand point that would properly describe such test plan.

As far as I understand, you have a testplan that usually you execute with JMeter via command line by specifying the `-J THREADS=X` option, is that right? If so maybe the resulting DSL code would be something like this?:

```java
public class PerformanceTest {

  @Test
  public void testPerformance() throws IOException {
    TestPlanStats stats = testPlan(
      threadGroup("${P__(THREADS, 1)}", X,
        ...
      )
    ).run();
  }
  
}
```

With such example, and if you use maven, to run the test you would require to use something like this to set the property:

```bash
mvn clean test -DTHREADS=Y
```

Or add some custom code in test code to set Java system property (for example from a file) or testplan jmeter property through `prop` method.

What do you think?

**Comment by QAInsights** [comment]
Yes @rabelenda That's correct. Instead of having this `${P__(THREADS, 1)}` in the code, how about adding the properties in a file or variables. The reason is, if we are using `${P__(THREADS, 1)}` in the code then, we need to wrap it with `parseInt`.

**Comment by rabelenda** [comment]
I think we can, and should, add support for strings, to allow using any jmeter expression you may like. Currently api supports ints since was considered to be the most used scenario, and avoid any potential issues, but for supporting jmeter expressions we would need String support as well (or some alternative mechanism, but so far we have opted to give String api for such scenarios). That would avoid `parseInt`, and in any case, you need to evaluate expressions in jmeter test plan execution time, not at "DSL test plan build time" which is what you actually code with java code in the DSL, unless you use some lambda injection in some of the DSL api methods that allow so.

Regarding support for a properties file, we can add something like `propertiesFile(String filePath)` to test plan (as we currently have `prop` method for a single property). That may be handy when you have different properties per environment.

**Comment by QAInsights** [comment]
Thanks @rabelenda for the insights. `propertiesFile()` would be ideal as you mentioned.

**Comment by rabelenda** [comment]
Hello,

We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.57) which includes both conversion of JMeter expressions in thread group properties and `propertiesFile` method in `EmbeddedJmeterEngine`. Please give it a try and let us know if you find anything that needs improvement.

Regards

**Comment by QAInsights** [comment]
On it @rabelenda :)

**Comment by rabelenda** [comment]
Closing since we haven't had any news, if you find something please let us know and we can re open or create a new issue.
