### ISSUE TITLE
[jmx2dsl] ClassNotFoundException: org.xbill.DNS.Resolver when importing a JMX that contains a DNSCacheManager

### ISSUE THREAD

**Issue by geraldpereira** [abstracta/jmeter-java-dsl#124]
Hi,

I get an exception using the `jmx2dsl` tool when importing a JMX file that contains a `DNSCacheManager` test element:

```
  <DNSCacheManager guiclass="DNSCachePanel" testclass="DNSCacheManager" testname="DNS Cache Manager" enabled="true">
    <collectionProp name="DNSCacheManager.servers">
      
    </collectionProp>
    <collectionProp name="DNSCacheManager.hosts">
      
    </collectionProp>
    <boolProp name="DNSCacheManager.clearEachIteration">false</boolProp>
    <boolProp name="DNSCacheManager.isCustomResolver">false</boolProp>
  </DNSCacheManager>
  <hashTree/>
```

This is a zip that contains the JMX file:
[buyer.zip](https://github.com/abstracta/jmeter-java-dsl/files/8940725/buyer.zip)

And here is the resulting stack trace:
```
java -jar jmx2dsl.jar Buyer.jmx
java.lang.IllegalArgumentException: Problem loading XML from:'/home/ubuntu/Dev/workspaces/jmeter-java-dsl-sample/Buyer.jmx'. 
Cause:
ClassNotFoundException: org.xbill.DNS.Resolver

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : java.lang.NoClassDefFoundError
cause-message       : org/xbill/DNS/Resolver
first-jmeter-class  : org.apache.jmeter.save.converters.TestElementConverter.unmarshal(TestElementConverter.java:98)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/DNSCacheManager
line number         : 47
version             : 0.57
-------------------------------
```

The JMX is imported without issue if I remove the `DNSCacheManager` test element.

**Comment by rabelenda** [comment]
Thank you for taking time to try it and report the issue.

Support for DNSCacheManager is currently not included in the DSL, and corresponding dependencies have been removed to reduce size, but we can easily release a patch version to avoid such error. You can, until the patch version is released, use as workaround something like:

```bash
java -cp /Applications/jmeter/5.4.3/lib/dnsjava-2.1.9.jar:jmx2dsl.jar us.abstracta.jmeter.javadsl.jmx2dsl.Jmx2Dsl buyer.jmx
```

In any case, you will get several `unsupported()` occurrences since some of the the features that you use in the test plan are either not yet supported by the DSL (like DNSCacheManager, AuthorizationManager & ConstantTimer) or are not yet covered by the converter (CsvDataSet, IfController, UniformRandomTimer, RegexExtractor & ForeachController).

We can easily add support for such elements or you can try sending a pull request. Let us know your thoughts.

**Comment by rabelenda** [comment]
We released a patch version which now includes the dnsjava jar, so you shouldn't get any longer the exception. Let us know about your needs regarding missing conversion.

I have an additional question: I have never had to use DnsCacheManager, do you use it for some particular reason?

**Comment by geraldpereira** [comment]
Thanks for adding the support for the DNSCacheManager.

Without it the dns cache is not cleaned between each thread and therefore the individual response times are distorted.

**Comment by rabelenda** [comment]
That is really interesting, thank you for the info. For the record, we didn't add support for DNSCacheManager yet (no conversion is done over it, and no DSL element has been implemented), the release (a patch version) only avoids the exception when converting the test plan.
