### ISSUE TITLE
Setting http request - protocol, server, port and path

### ISSUE THREAD

**Issue by ankugarg** [abstracta/jmeter-java-dsl#13]
Is it possible to set protocol, server name, port number and path of http request?

![image](https://user-images.githubusercontent.com/13931015/102720913-33606500-431d-11eb-9b71-b159a1c07763.png)

I'm only able to set complete URL in Path field only. And unable to set other fields via library.

**Comment by rabelenda** [comment]
Hi,

We really appreciate the interest on the library and taking the time for reporting issues and asking questions & new features. Thank you.

Regarding your request: can you elaborate on how you plan to use such fields and why you need to specify them separately? 

Currently, as you mentioned, and to keep the API simple, the library only supports specifying the full URL. So, in the scenario you want to specify the host, port & path, you can build an URL and pass that to the httpSampler. 

If you help us understand better your needs and reasoning, we could evaluate adding methods to be able to specify each field independently (instead of specifying them in the URL).

Regards.

**Comment by ankugarg** [comment]
Hi,

Thanks for responding.


```java
// below 4 samplers part of threadGroup1 
DslHttpSampler sampler1 = httpSampler("sampler1", "https://server1.io/v2/store/order/1");
DslHttpSampler sampler2 = httpSampler("sampler2", "https://server1.io/v2/store/inventory");
DslHttpSampler sampler3 = httpSampler("sampler3", "https://server1.io/v2/user/createWithArray");
DslHttpSampler sampler4 = httpSampler("sampler4", "https://server1.io/v2/user");
// below 1 sampler part of threadGroup2 
DslHttpSampler sampler5 = httpSampler("sampler4", "https://server2.io/v2/userList");
```
In samplers, from 1 to 4 there is duplicacy which can be avoided.

It's possible to use variables for protocol, server but was wondering if it could be achieved with below code:
```
DslHttpSampler sampler1 = httpSampler("sampler1", "v2/store/order/1");
DslHttpSampler sampler2 = httpSampler("sampler2", "v2/store/inventory");
DslHttpSampler sampler3 = httpSampler("sampler3", "v2/user/createWithArray");
DslHttpSampler sampler4 = httpSampler("sampler4", "v2/user");
threadGroup(1, 1, sampler1,sampler2,sampler3,sampler4).setProtocol("https").setServer("https://server1.io").setPort("80");
``` 
httpSampler API can accept either full url or path/endpoint.

**Comment by rabelenda** [comment]
One way to achieve this with current version of jmeter-java-dsl is just using java variables, for example:

```java
String server1BaseUrl = "https://server1.io/v2";
String storeBaseUrl = server1BaseUrl + "/store";
DslHttpSampler sampler1 = httpSampler("sampler1", storeBaseUrl + "/order/1");
DslHttpSampler sampler2 = httpSampler("sampler2", storeBaseUrl + "/inventory");
String userBaseUrl = server1BaseUrl + "/user";
DslHttpSampler sampler3 = httpSampler("sampler3", userBaseUrl + "/createWithArray");
DslHttpSampler sampler4 = httpSampler("sampler4", userBaseUrl);
DslHttpSampler sampler5 = httpSampler("sampler4", "https://server2.io/v2/userList");
```

That would be simple, but I don't know if is enough for your needs or is there any particular need that I am not identifying right now.
By doing that the exported JMX (if you need to export to JMX) will have the URL duplicated in each sampler, but that shouldn't be much of an issue unless you intend to improve the maintainability of the JMX file by using variables or common settings.

In JMeter in general, this reusability is in general achieved by the usage of [JMeter user defined variables](https://jmeter.apache.org/usermanual/component_reference.html#User_Defined_Variables) (which jmeter-java-dsl does not yet support, but might be a good addition) in conjunction with variable references (like `${HOST}`) or using [HTTP request default element](https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Request_Defaults) (which again jmeter-java-dsl does not yet support but we could implement as a new addition).

Please let me know if the provided solution with Java variables is good enough, or if you think some of the other options (implementing a new feature) is more suitable for your use case, and why you think so.

Thank you very much for giving us additional context and we are eager to hear more about this topic.

**Comment by ankugarg** [comment]
Sorry for late response.

**HTTP request defaults element** support would be great if could be implemented in jmeter-java-dsl.

Thanks for your continuous help.

**Comment by rabelenda** [comment]
Hello,

Are you interested in the HTTP request defaults element support for some particular reason? Do you prefer it over using java variables for some reason?

I just want to understand your use case, to provide the best and simplest solution for everyone.

Best regards

**Comment by ankugarg** [comment]
HTTP request defaults would reduce duplicacy in generated JMX files.

You are right. For tests in Java, variables should be preferred approach.

**Comment by rabelenda** [comment]
Hello,

The main purpose of the library right now is for allowing to implement performance tests in java by reusing JMeter functionality. The JMX generation is feature that we added as a back door when currently provided features in the library are not enough and you need to use JMeter GUI instead, and also to facilitate using cloud services (as BlazeMeter). So, for the time being we prefer keeping the provided API simple over providing additional features that would make the JMX cleaner in some cases.

We are doing this, since is what we think is more important right now, and for the use cases we have seen and used. If you have some particular use case that would significantly benefit from providing such support, please let us know. We are eager to understand and support new use cases, and even reconsider the vision/purpose of the product/library.

Eg: maybe in your team you have some people developing tests with the library, but generate JMX so other team members can use tests written in dsl as a base and then use GUI for other cases. Or maybe you are missing some particular JMeter feature in dsl (if this is the case, please let us know which is the feature and we would evaluate providing support for it instead) and right now need always to export to JMX to complete the test.

Thank you very much for your patience & understanding. And thank you for bringing your point of view and ideas.

Regards

**Comment by ankugarg** [comment]
Thanks for the detailed explanation.
