### ISSUE TITLE
Getting the total response time of all the requests

### ISSUE THREAD

**Issue by aabirdaneshyar** [abstracta/jmeter-java-dsl#15]
Hello,

In my test scenario I have thread count of 100 and I want to calculate the total response time of all the requests. 
Is there a way by which we can achieve that ?
I have tried using elapsedTime() method but it returned only 1 milli second. [PT0.001S]
This was not the case when the same scenario was tried using Jmeter UI. From Jmeter UI it took around 2000 milli seconds

Code snippet is as follows-

`public class Test2 {

	@Test
	public void test() throws IOException {
		
		JsonObject postObject = Json.createObjectBuilder()
                .build();
		
		TestPlanStats stats = testPlan(
			      threadGroup(100, 0,
			        httpSampler("https://reqres.in/api/users?page=2")
			        .children(responseAssertion().containsSubstrings("Ok"))
			        .header("Authorization", "Basic ")
			          .post(postObject.toString(), Type.APPLICATION_JSON)))
				.run();
		        System.out.println(stats.overall().elapsedTime());
			   
			  }
	}`

Thanks and Regards
Aabir

**Comment by rabelenda** [comment]
Hello,

In the example you provided you set to use 100 threads with 0 iterations, which will make each thread don't do anything. Take into consideration that this is usually not what you want to do, you want each thread to do at least 1 iteration (in the example you provided at least 1 http request).

Please try changing the number of iterations and let me know.

Regards

**Comment by aabirdaneshyar** [comment]
Sorry I thought that was the Ramp-up time parameter.

After changing that to 1 and running the test again I got elapsed time figure of around 4 seconds.
But, if you run the same test on Jmeter UI using the .jmx file then the corresponding elapsed time figure would be around 2 seconds (roughly double). Can you please help me understand why am I getting this difference ?
I have attached the jmx file in the text format for your reference. 

[FirstTest.txt](https://github.com/abstracta/jmeter-java-dsl/files/5735512/FirstTest.txt)


Thanks

**Comment by rabelenda** [comment]
Hi,

There is a slight difference between the two items you highlight:
* The one in the UI displays the time the test has been running in UI (since you hit start until it ends)
* The one your are displaying in jmeter-java-dsl is displaying the time difference between the first and last request.

The second one should be (in general) lower than the first one, and not the other way around (as you are experiencing).

Can you try putting JMeter UI logs in debug level and dump results to a JTL file (with simple data writer), and do the same in jmeter-java-dsl (with jtlWriter and configuring log4j2.xml setting as described in readme). 

The first thing to check is if you are getting similar information in JTL (similar response times). If you aren't getting similar response times, please share the files to be able to trace the potential reason and fix jmeter-java-dsl accordingly (there could be a difference in how UI handles connections if we are missing setting some default config in JMeter engine). 

If you are getting similar responses, then it might be on JMeter execution, and that would require deeper analysis. If you can, please share the logs (feel free to scramble any potentially sensitive information) so we can analyze it and help you trace the issue (potentially fixing jmeter-java-dsl if anything is not properly working).

Thank you very much for taking the time of reporting the issue and sharing all the data to allow us help you in this regard.

Regards

**Comment by aabirdaneshyar** [comment]
Hello,

I ran those tests again on Jmeter UI and Jmeter-dsl and still observed the difference in the response time. 
I am attaching the jtl, log and report files of both the platforms in a zip format.

One more thing I observed - that if you run the test using dsl with <Root level="info"> in log4j2.xml then the response time is around 4 seconds while if you run the tests with <Root level="debug"> then response time is around 8 seconds. 

[jmeter-files.zip](https://github.com/abstracta/jmeter-java-dsl/files/5736793/jmeter-files.zip)


[dsl-files.zip](https://github.com/abstracta/jmeter-java-dsl/files/5736794/dsl-files.zip)
 

Regards
Aabir

**Comment by aabirdaneshyar** [comment]
Please let me know if you need any more information from my side


Thanks and Regards

**Comment by rabelenda** [comment]
Hello,

Thank you very much for all information that you have shared and bringing this important topic.

I ran some tests, and got similar results using IntelliJ runner & maven. But after changing maven to not fork JUnit tests (`-DforkCount=0`) and running JMeter in non GUI mode (eg: `bin/jmeter -n -t ~/Downloads/my-test.jmx` ), which is the advised way of running it for performance testing, some times I am getting faster responses when running with maven and some times faster with JMeter, so it seems settings are comparable/analog. 

I guess that the issue might be related to JVM & class loading, for instance, when you use JMeter GUI it pre loads some classes that are later used for execution, so their loading cost does not affect performance testing. This is just some guessing (would need to do a deeper and costlier testing to properly evaluate the reason), and would highly depend on your machine setup, JVM, etc. A similar thing may be happening when using maven with fork mode, since the additional JVM instance start up load might be impacting the test results.

Regarding the test, in general is advisable to use a ramp up time (to avoid thread creation load impacting test results), and use a longer running test to get statistically better metrics (by using more samples) than a shorter one. In general, prefer setting big enough iterations (depending on the flow & number of threads, I would say something above 100), instead of increasing number of threads to increase number of samples. Threads should be used to control how many concurrent requests you want to impose to the service/server, and iterations to control how many requests. Also take into consideration that JMeter, by default, automatically resets HTTP connections between iterations, so it would properly emulate different users (instead of one user doing the same flow each time, which can be done with a loop controller instead) just using 1 thread with multiple iterations (but requests wouldn't be done in parallel though).

Regarding jmeter-java-dsl, it doesn't still allow you to set up a ramp-up period, but we can easily add such feature.

Please let me know if anything of this helps, and if you still experience same behavior after reviewing and applying some of the changes I mentioned to you, please let me know.

Regards

**Comment by rabelenda** [comment]
Regarding logs: yes, whenever you increase logging it is expected to impact general load generated by the test execution, which will impact metrics. So in general is good to keep logging low (info, warning or above), and only use debug when you want to trace something.

**Comment by rabelenda** [comment]
An additional thing that might be affecting your test executions might be your JVM settings, for example heap memory. JMeter by default specifies some settings that are not the default ones for the JVM. Eg, in java 8 & JMeter 5.2.1 I am getting these settings: `-server -XX:+HeapDumpOnOutOfMemoryError -Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m  -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:G1ReservePercent=20`. Depending on your machine specs and how you run the tests, you might be using lower memory than what JMeter uses by default. In maven you can use `MVN_OPTS` flag to set this properties when using `forkCount=0`, or "-DargsLine=" setting when not.

**Comment by rabelenda** [comment]
In case you want to experiment with setting ramp-up periods, we have just released a new version of jmeter-java-dsl which allows to set them.

Regards

**Comment by aabirdaneshyar** [comment]
Thanks a lot for the detailed explanation. 

I will definitely try this out during the weekend and share the results with you.

**Comment by aabirdaneshyar** [comment]
Hello,
I ran the tests again using Jmeter-java-dsl with forkCount = 0 and jmeter on non GUI mode and results of both of them were similar.


Thanks

**Comment by aabirdaneshyar** [comment]
Just one more quick question.
 For a single request (thread count = 1) it takes about 2 seconds in Jmeter and jmeter-dsl but only about 500ms in Postman. 
why do we experience such a difference in response time ?


Thanks

**Comment by rabelenda** [comment]
Hello, 

I am not sure, and would need to run some tests to confirm. But I guess it would also have to do with initialization phase being expensive in JMeter, as opposed to Postman. Network time should be comparable (you may review this with a tool like wireshark), but initialization phase (on client/jmeter/postman side) might be considerable different, taking into consideration the different environments they run (one running in a chromium based environment, and the other running in java with httpclient). Postman may be using some native socket interface, or pre initialized structure that might be faster to initialize than java interface (and HTTP library) used by JMeter. 

Would be really interesting to trace why initial request takes so considerable time (compared to PostMan). I may review later on if I find something considerable here, but you could use visualvm or mission control to do a profiling if you prefer (but understanding the results could be challenging, and would require knowledge on jmeter code & the jvm).

One option you may try is changing the default http client implementation used by JMeter (and in consequence jmeter-java-dsl), and see if you get any considerable difference. 

For that, you can set jmeter property `jmeter.httpsampler` to `Java` like this:

```java
System.setProperty("jmeter.httpsampler", "Java");
```
