### ISSUE TITLE
To ability to write in influxDb

### ISSUE THREAD

**Issue by BojteTamas** [abstracta/jmeter-java-dsl#2]
If this is possible we can combine the influxDb and Grafana to obtain very nice graphics.
Possible you can get some data from here : https://github.com/NovatecConsulting/JMeter-InfluxDB-Writer

**Comment by rabelenda** [comment]
Cool, it sounds like a nice addition. But for reporting metrics is probably better to just implement support for [JMeter backend listener](https://jmeter.apache.org/usermanual/realtime-results.html). The module you describe seems more intended on doing load test on InfluxDB instance instead of collecting test metrics and sending them to InfluxDB. What do you think?

We will take into consideration the implementation of backend listener in the meantime.

Please if anyone else is interested in this feature let us know.

**Comment by rabelenda** [comment]
Please check [the latest release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.4) and let us know.

**Comment by BojteTamas** [comment]
Thank you! You were very fast! It is working properly.
![Screenshot_10_27_20__12_34_PM](https://user-images.githubusercontent.com/9676903/97290086-c1a1f880-1850-11eb-8ccc-041084faab72.png)

**Comment by rabelenda** [comment]
I am glad that it is what you expected. Let us know of any other nice ideas :-).
