### ISSUE TITLE
Java sampler - performance testing of Java request

### ISSUE THREAD

**Issue by amitoverflow-ui** [abstracta/jmeter-java-dsl#22]
Is it possible to do performance testing of Java code?

**Comment by rabelenda** [comment]
Hello, thank you for asking this.

Can you further elaborate on what type of java code you want to execute a performance test on, so I may be more helpful? 

Currently the DSL does not provide a built in way for measuring Java code execution, but we will consider it for next release, so stay tuned :-).

Take into consideration though that Java Request & JSR223 Sampler which are usually used in JMeter to run performance test with custom Java code, are intended in general, as is JMeter in general, more towards testing time spent in interaction with an target service (through potentially custom java code), and may not be good or as efficient as other tools for running micro benchmarking on a particular java code piece. If you intend to do micro benchmarking you might want to explore jmh ([here](https://www.baeldung.com/java-microbenchmark-harness) are some samples of it's usage) or similar tools.

Hope to hear back from you to get more insights on your particular needs.

Regards.

**Comment by amitoverflow-ui** [comment]
Hi,
Thanks for quick response.
I don't want to java micro benchmarking. Want to test Java API's with huge user load. 

Below is sample code/approach:
```
public class MySampler extends AbstractSampler {
@Override
	public SampleResult sample(Entry e) {
		SampleResult sampleResult = new SampleResult();
		sampleResult.sampleStart();
		try {
			// test code -> calling Java API's via reflection
			sampleResult.sampleEnd();
			sampleResult.setSuccessful(Boolean.TRUE);
			sampleResult.setResponseCodeOK();
			sampleResult.setResponseMessage("Pass");
		} catch (Exception ex) {
			sampleResult.sampleEnd();
			sampleResult.setErrorCount(1);
			sampleResult.setResponseMessage(ex.getCause().getMessage());
			sampleResult.setSuccessful(Boolean.FALSE);
		}
		return sampleResult;
	}
}
```

Please let me know if more details are needed.

**Comment by rabelenda** [comment]
Hello,

We have just released a new version of the DSL that adds support for `jsr223Sampler`. You can check the [new user guide section](https://abstracta.github.io/jmeter-java-dsl/guide/#java-api-performance-testing).

I hope this helps. Let us know of any comments or questions.

Regards

**Comment by amitoverflow-ui** [comment]
Thanks

**Comment by polarnik** [comment]
Hello! But **Java Request** has a better performance than **jsr223Sampler**. And **Java Request** also has a better UI for passing parameters than **JUnit Request**.

Root of performance problem is a process of creating Binding (shared context, shared import sections, etc) on each iteration :
```java
Bindings bindings = scriptEngine.createBindings();
```
https://github.com/apache/jmeter/blob/v5.5-rc1/src/protocol/java/src/main/java/org/apache/jmeter/protocol/java/sampler/JSR223Sampler.java#L70

**Comment by rabelenda** [comment]
Hello @polarnik and thank you to rise this concern!

As far as I see the line you highlight only creates internally a hashmap, maybe you meant the [populateBindings](https://github.com/apache/jmeter/blob/1efebb753d52b90c7e569534d7b4518dbaa60b76/src/core/src/main/java/org/apache/jmeter/util/JSR223TestElement.java#L167) instead?

Do you have any measure of the performance impact of jsr223Sampler over JavaRequest?

It is highly probable that javaRequest is more performant than jsr223Sampler since it doesn't have to use groovy engine to run (which adds a layer of processing to java code). On the other hand, I think jsr223Sampler is a little simpler to use, since you don't have to declare arguments that you are going to use to later on populate them, nor implement a specific interface with several methods (except when you use java labmda which is in fact an interface, but a simpler one thant JavaRequest). 

But aside from all this, it might be a good addition, since avoid unnecessary groovy engine execution, and enforces good practice of thinking in setup & teardown.

Maybe you can open a new issue to add support for JavaRequest as well and further explain your points?

Thank you very much to take the time to review this and give your point of view.

**Comment by polarnik** [comment]
Hello @rabelenda
Thank you very much to take a quick response and to highlighting java lambdas.
I will try use Java lambdas instead of Groovy script.

You are right. I meant about populateBindings instead of createBindings.
Ok I will create some benchmarks

See you

**Comment by kirillyu** [comment]
Will there be an improvement in performance if lambda expressions are used? If so, could you expand the answer

**Comment by polarnik** [comment]
Hi @kirillyu 
lambdas call this [code](https://github.com/abstracta/jmeter-java-dsl/blob/v0.51/jmeter-java-dsl/src/main/java/us/abstracta/jmeter/javadsl/core/util/DslScriptBuilder.java#L73-L77):
```java
  private static String buildScriptString(String scriptId, Class<?> varsClass,
      Map<String, String> varsNameMapping) {
    return "props.get('" + scriptId + "').run(new " + varsClass.getName() + "("
        + buildConstructorParameters(varsClass, varsNameMapping) + "))";
  }
```
it is like groovy jsr223 script:
```groovy
props.get('123').run(new test123(1, 2, 3))
```
without an improvement in performance.

May be this code has a better performance (without locks, etc):
```groovy
vars.getObject('123').run(new test123(1, 2, 3))
```
We need some benchmarks

**Comment by polarnik** [comment]
Short test results:

- jsr223Sampler - 30900 rps, average duration: 0.02 ms (it is possible: 1 / 0.02 ms = 50000 rps)
- dummySampler - 90900 rps, average duration: 275.04 ms (it is impossible: 1 / 275.04 ms = 3.63 rps)

dummySampler is faster, but with dirty duration time - duration time of dummySampler contains some errors
jsr223Sampler is slower, but with clear duration time

```java
threadGroup(1, 2000000,
        onceOnlyController(
                jsr223Sampler("test1", v -> {
                    v.vars.putObject("run", new TestJavaObject().setSamplerVars(v));
                })
        ),
        jsr223Sampler("jsr223Sampler", v -> {
            TestJavaObject t = (TestJavaObject) v.vars.getObject("run");
            t.run();
        }),
        dummySampler("dummySampler", "${__jexl3( vars.getObject('run').run(),)}")
)

...

public class TestJavaObject extends AbstractScenario {

    @Override
    public String run() {
        return null;
    }
}
```

jsr223Sampler:
<img width="1507" alt="jsr223Sampler" src="https://user-images.githubusercontent.com/7660287/163275319-dd2faa1f-54f4-4e10-9bf0-7a72f062d4f7.png">

dummySampler:
<img width="1507" alt="dummySampler" src="https://user-images.githubusercontent.com/7660287/163275225-fc245757-c313-4fd3-9373-6a3d4d1d99b0.png">

**Comment by rabelenda** [comment]
Interesting, maybe is related to caching, or maybe is about speed of execution and GC interveaning? the jsr223Sampler will cache the compiled script, while the dummySampler you posted will re parse the function every time. Maybe a better way to test it is just using some lambda instead of JMeter expression, but that would require some custom DSL element or extension/modification.

**Comment by rabelenda** [comment]
@polarnik you might be interested in [latest release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.14).
