### ISSUE TITLE
 Support for Prometheus Listener for generating Grafana dashboard

### ISSUE THREAD

**Issue by rahul84gupta** [abstracta/jmeter-java-dsl#258]
Please include Prometheus Listener for generating Grafana dashboard using Jmeter-DSL.

**Comment by rabelenda** [comment]
Thank you for bringing this request. 

Please, if anyone else is also interested in this feature, upvote it so we know the community interest in this.

Regards

**Comment by IvanKvashnin** [comment]
+

**Comment by Rasta341** [comment]
upvote :) that must be usefull

**Comment by sergeykrylovich** [comment]
upvote!

**Comment by SubbotinMXM** [comment]
upvote

**Comment by sk0ba** [comment]
Upvote! 
Usefull feature!

**Comment by KKoblukov** [comment]
Upvote pls!

**Comment by dimkor** [comment]
Upvote!

**Comment by mrRazmarin** [comment]
upvote!

**Comment by zakamaldin** [comment]
Upvote!

**Comment by rabelenda** [comment]
Wow, I see a lot of people interested in this feature :).

Any particular reason to prefer Prometheus over an alternative like influxDB?
Can you provide some example jmx of how you use the listener?
What metrics do you usually use? 
Can you provide a grafana dashboard that you usually use in combination with the plugin?

How do you usually handle the potential issue of losing metrics due to the "pull" nature of Prometheus? 
For example, if you have you prometheus server polling metrics every 5 seconds, how do you avoid losing the metrics for the last 5 seconds of JMeter test plan execution in your Prometheus metrics? 
I see the plugin [doesn't have a way to push metrics](https://github.com/johrstrom/jmeter-prometheus-plugin/issues/23). 
Do you usually set `prometheus.delay` system property, to be greater than prometheus server poll period?

**Comment by rabelenda** [comment]
We have just released [a new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v1.28) which includes `prometheusListener`. I will close this issue. Feel free to re open it if you have further questions/comments regarding this.
