### ISSUE TITLE
Parallel controller

### ISSUE THREAD

**Issue by EugeneKazakov** [abstracta/jmeter-java-dsl#32]
Hi there!
Would be great to see the parallel controller by BlazeMeter https://github.com/Blazemeter/jmeter-bzm-plugins/blob/master/parallel/Parallel.md in the DSL

**Comment by rabelenda** [comment]
Hello,

Thank you very much for asking for it and taking the time to look into the DSL and creating this issue!

Can you give an example about when you usually use the parallel controller?

What are the key parallel controller properties/features you think the DSL must include in the first release of this feature?

Regards

**Comment by EugeneKazakov** [comment]
We use the parallel controller when we need to emulate sending requests in parallel
All the features are needed

**Comment by rabelenda** [comment]
Hello,

Might your use case be covered by using downloadEmbeddedResources of httpSampler? Are the parallel requests generated due to embedded resources in a HTML resource and you want to emulate same browser behavior? Or are you simulating client code/API invocation that generates requests in parallel? Might your use case be covered by using separate thread groups?

I ask this questions to keep the API simple, and avoid adding components for use cases that might be covered by existing features. I do see cases where parallel controller is needed, but in most scenarios they are not needed.

Thank you very much for your time and info, hope to hear back from you soon.

Regards

**Comment by kirillyu** [comment]
Hm, but for parallel you really can use separeted threads, no?

**Comment by EugeneKazakov** [comment]
this is for a case when the client-side of a single user sends the requests in parallel
it's not like embedded resources or so

**Comment by rabelenda** [comment]
Thank you very much @EugeneKazakov , we will consider it for next release. Stay tuned.

**Comment by EugeneKazakov** [comment]
wow, that was fast, thanks a lot! @rabelenda

**Comment by rabelenda** [comment]
We just released [another version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.31) with improvements on original design of the DSL for parallel controller.
