### ISSUE TITLE
RpsThreadGroup issues

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#33]
1. How to execute .saveAsJmx("path") on RpsThreadGroup? 
I see this message `The method saveAsJmx(String) is undefined for the type RpsThreadGroup`
2. There is different tree building variants in threadGroup and rpsThreadGroup example:
`threadGroup(1, 1,
              httpSampler("label","/api/list")
)`
and only
`rpsThreadGroup()
            .children(httpSampler("label","/api/list"))
`
So why I can't put childrens in round brackets? It seem's stange and non-universal, but not crit.

**Comment by rabelenda** [comment]
Hello,

1. The method `saveAsJmx` is defined at test plan level. Do you have any particular need to save a JMX with part of the testplan instead of the entire testplan?

2. In general the rule we follow is: if we can provide a simpler way for most commons scenarios to configure an element, then we provide it right in builderMethod (by providing for example in thread groups, common config parameters and children), but, if configuration is more complex (like in rpsThreadGroup), then separate it, always setting config first and children elements.
`threadGroup` also provides the builder without constructs. You can see that threadGroup() when used with rampUps and holds is mostly the same as rpsThreadGroup. The two scenarios where they differ is when you use just iterations or duration, for which we provide built in builder with children for faster/less verbose usage. 
We understand this is not be consistent in 100% of cases (in some cases you pass children in builder method, in some other in children method), but alternative would make most of simple scenarios unnecessarily verbose, eg: `threadGroup().threadsIterations(1,1).children(...)` and `threadGroup().threadsDuration(1, Duration.ofSeconds(5)).children(...)` OR `rpsThreadGroup(RpsThreadGroupConfig.rampUpToAndHold(10, Duration.ofSeconds(5)).maxThreads(10), httpSampler(...))`.

If you have any other ideas or comments we will be to review them.

Regards

**Comment by kirillyu** [comment]
.saveAsJmx is working, my bad)
About second problem - I understood your position, I think it;s OK
