### ISSUE TITLE
Functionality Questions

### ISSUE THREAD

**Issue by MrThreepwood** [abstracta/jmeter-java-dsl#6]
I'm running into a few problems attempting to figure out how to do things/how things work. We're currently using Gatling which is fairly inconvenient due to it being in Scala and seems to lack simple programmatic access to results/no instructions for running it outside the gatling compiler which automatically runs.

I'm seeing the jtl output file, but I was hoping to completely avoid any need to interact with Jmeter at all. Is there an easy way to turn that simple CSV into an HTML report?

Also, is there a way to access the results of each http request programmatically? One thing I'm wondering about is how I'm supposed to tell whether a network request failed or not. Obviously I have the error count, but how does it decide what is and isn't an error? If I'm trying to test an endpoint that we've intentionally rate limited to avoid load on the system from bad actors, how can I tell if a load test is still overwhelming it with too many requests vs. it simply returning a standard rate limit error response?

Ideally I'd like to be able to loop over each request and make assertions about the results programmatically, but I believe Gatling has something that allows you to define a function that you can pass to define whether or not a call was a success or failure. Is there something similar here?

**Comment by rabelenda** [comment]
Hello, 

we have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.6) including support for JSR223 post processors, which allows you to control error reporting for sample results, and also adds a simple way to generate HTML reports. 

Please check the associated examples in [use cases documentation](https://github.com/abstracta/jmeter-java-dsl/blob/master/docs/use-cases.md) and let us know if this is enough for what you need, or if you have any particular requirements or any comments.

Regards

**Comment by MrThreepwood** [comment]
Thanks for responding so quickly. Building the HTML reports logs this a lot:
`Cannot write to 'blah/html-report' as folder is not empty`
This happens regardless of whether or not the folder is empty (or even exists). It does eventually appear to work if it is empty though. It never works and just hangs on that step if it is not empty. It might be good to automatically make sub directories under the directory using a unix timestamp for each run? It's not too hard for the user to provide a directory for that I suppose. It's a little strange that I still get that error even when the directory is empty/doesn't exist.

The JSR223 processor is nice, but I don't suppose there's a way to do it more programmatically is there? I looked at the implementation and I didn't see an obvious way to actually get the response and just process it in code. Not having access to code completion makes that bit a little painful.

I'm also not sure how to chain requests? For example, make a login request and then use the auth token response in the next call in the chain? If this is something that's not yet supported but is doable I'd be happy to submit a PR if you can point me in the right direction.

**Comment by rabelenda** [comment]
Hello,

I have tested several times and have only received such an error when the directory is not empty. Can you provide more info when do you receive such a message? Maybe do some debugging or logging?

Aside from that, I now see that the provided example in use cases document is not good, and users would regularly face such an issue with current implementation. I will add validation in htmlReporter input as to get the feedback sooner, and will better document the restriction and change the example.

When designing the htmlReporter I thought about implementing some mechanism for "appending" reports in a directory (adding dates for example). But I decided to just ask for the target directory where the user will expect the actual report (index.html) to be located, and leave it to the user to define the final structure for collecting several reports, keeping also the logic of the library simple. 

If you intend to run periodic reports or several runs, as commented in use cases document, I encourage you to try and consider the InfluxDB + Grafana option, which is more complete and powerful than the standalone HTML reports.

About the JSR223 post processor and auto complete, I agree, current provided implementation is simple and allows to use JMeter provided functionality as is, but is not optimal for the user experience (in fact we started exploring alternatives right after publishing the release). We will continue exploring ways to improve this. If you have ideas please let us know :-).

About your final point, this is usually done though the usage of Extractors and JMeter variables. We haven't implemented yet because nobody has yet asked for it :-) (that is the general policy we are following, implementing features/support as users ask for it, following KISS and YAGNI principles). The most common extractor used is [Regular Extractor](https://jmeter.apache.org/usermanual/component_reference.html#Regular_Expression_Extractor) and you can get more information on the usage of variables [here](https://jmeter.apache.org/usermanual/functions.html). If you need a guide on how to implement support for them in jmeter-java-dsl, you can take a look into [Jsr223PostProcessor implementation](https://github.com/abstracta/jmeter-java-dsl/blob/master/jmeter-java-dsl/src/main/java/us/abstracta/jmeter/javadsl/core/postprocessors/DslJsr223PostProcessor.java) (extractors are just another type of post processors) and the [contributing guide](https://github.com/abstracta/jmeter-java-dsl/blob/master/CONTRIBUTING.md). 

We can easily implement such support, so let us know if you want to submit the PR, or want us to do it. We would prefer you submitting the PR as to increase the number contributors, but we understand that it may be a little daunting for someone with no JMeter experience. You can take a look and let us know, if we don't hear from you, we will implement it at the beginning of next week (if plans don't change :-)).

Thank you very much for your thoughts, reports and requests for features. They are great input for us to prioritize work to be done.

Regards

**Comment by MrThreepwood** [comment]
Thanks, this is the same issue I had on my other ticket (I had a repeat at the bottom of the test). For the writing to the directory, it's more so that it's a nuisance for me to delete the contents every time I want to tweak my tests and look at the results, but I can make my own function to clear the directory before each test I suppose.

As for the response processing we were hoping to find a way to use these for both continuous health checks and load testing by simply changing the number of iterations. Being able to examine the contents of the response and validate that it is what we expected would be valuable to us (but I recognize that this is a fairly Pie in the Sky expectation).

Mostly I was just excited about the simple way we can run the tests and get results, where standard Gatling and JMeter are VERY standalone and don't integrate with tests/existing code bases well.

**Comment by rabelenda** [comment]
Hello, is there any pending request/feature in this issue? or should we close it?

**Comment by rabelenda** [comment]
We have released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.8) which includes regex extractors, you might want to have a look at it.
