### ISSUE TITLE
forLoopController, integer param of loop

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#66]
It's has no variants how to push the variable in loop count param.

**Comment by rabelenda** [comment]
Hello, thank you for asking for this.

What particular scenario are you thinking this could be useful?

Regards

**Comment by rabelenda** [comment]
Can you provide some code examples and comparison with while controller, to identify if the difference would be worth it? I am a little concerned about adding a feature that maybe is already covered by some existing component, and has no clear difference, which might confuse users in the end (when to use while vs when to use for with dynamic condition).

Thank you very much for clarifying this.

**Comment by kirillyu** [comment]
of course you can do everything in while controller, but in fact we already have forLoopController. so there is not question what we can do in while, but can't do in for. there is another question: why I should use while instead of use for? because of while has better implementation and no limitations of usage. I try to say, that we can change questions to "why it easier to use?"
and there is i think much easier answer. this answer has already been given many times:
in programming languages we have for, while and foreach which can be configured via script. and all of them are used.

**Comment by rabelenda** [comment]
I do see your point but:

I think the reason for having a for loop in programming languages is different from JMeter, mainly because jmeter already provides a built in variable for iterations in whiles. Regarding of existence of forLoopController and whileController in DSL, I thought of for loops as really simple way of executing a defined/fixed number of iterations (just specifying the number), vs while allowing for dynamic conditions.

Are you considering using forLoopController with a variable expression for any particular use case? I think having a code example could greatly clarify a use case where might make sense to use forLoopController with variable expression, instead of using whileLoopController.

As we have discussed in the past, I try to keep the api simple (don't provide too many options to do one thing and potentially unnecessarily confuse users while also keeping maintenance efforts low), while at the same time keep it intuitive to users and not limited for complex scenarios. In general I think something like: provide simple ways to do simple and/or common things, and complex / rare cases might require additional effort / code.

Please if you can provide and example code where you usually use variable expression in for loop, that would help a lot.

Thank you very much for bringing this to attention, and spend time to discuss it and try to expose your point.

Regards

**Comment by kirillyu** [comment]
I can give an infinite number of examples, but as far as I understand, we need an example that is really in demand. Not synthetic.

The problem is that for non-synthetic and real examples, you need to give a huge amount of context. Explain the specifics of decisions, etc. Otherwise, they are all not indicative of features for the end user.

Base problem - we can not push the jmeter variable to loop count paramenter. It means that if anybody have any value in jmeter in vars map and thay want to push it in loop -> they should use while and it means, that everybody should know about $__jm__{loop_name}__idx or they should to use another variable as iterator. 

Code example:
```
    TestPlanStats stats = testPlan(
            threadGroup(12, 1,
                        jsr223Sampler(v -> {
                            String result;
                            switch (v.ctx.getThreadNum() % 3) {
                                case 0: result="10";
                                case 1: result="100";
                                default: result="0";
                            }
                            v.vars.put("count",result);
                        }),
                        forLoopController("${count}",
                                          httpSampler("host.io"))
            )
        ).run();
```

**Comment by rabelenda** [comment]
Ok, yes I see your point.

In general looks like most of such scenarios would instead be covered by forEachController, since usually when you want to iterate a runtime defined value of iterations you want to iterate over entities returned by previous entity.

I understand that in some cases, you may want to iterate some runtime defined of times according to more complex logic, and doing it with whileController would mean more code (adding the variable comparison condition) than using a forLoopController with a variable.

We will consider this feature for following release.

Thank you very much @kirillyu for taking time to explain it and give an example, you are always very considerate by explaining the reasoning and bringing all these requests and ideas into consideration.

Regards

**Comment by kirillyu** [comment]
Thank you. I think the dsl became popular because of your attentiveness and thoroughness in all matters. I wish you patience)

**Comment by rabelenda** [comment]
Hello,

We just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.46) which adds support for setting JMeter expressions (like `"${MY_LOOP_COUNT}"`) in `forLoopController`.

We hope this fits your needs.

Regards
