### ISSUE TITLE
preproccessor sample class

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#78]
In docs I see that the "sampler" in jsr223PreProccessor is implemented by class[ HTTPSamplerBase](https://jmeter.apache.org/api/org/apache/jmeter/protocol/http/sampler/HTTPSamplerBase.html#addArgument(java.lang.String,%20java.lang.String)), but i see that is another implementation: [Sampler](https://jmeter.apache.org/api/org/apache/jmeter/samplers/Sampler.html) (I can be wrong). 

What the problem? In lambda realisation I can't use HTTPSamplerBase methods like setProxyHost("") or etc.

**Comment by rabelenda** [comment]
When you say in docs, do you refer to DSL java docs, DSL user guide, or jmeter docs?

If you know the sampler is an http one, have you tried casting it? E.g.: `((HTTPSamplerBase) s.sampler).setProxyHost("..")`.

Regards

**Comment by kirillyu** [comment]
JMeter docs, yes. Hm, casting? Casting is works fine, but seems stange and non-obvious. Is that necessary to implement it like this?

**Comment by rabelenda** [comment]
Hello, can you point me to the JMeter docs where you see such reference?

Regarding the casting, well, yes, remember that java is strongly typed and that JMeter supports not only http samplers but also other types of samplers which may not have the setProxyHost (in fact, setProxy is not a method shared by all samplers), and there is no way for the pre processor to know that is applied to http sampler to automatically cast (since pr processor might be applied to a set of samplers by adding it as sibling or up in the tree). Long story short: for java the cast is required to use setProxyHost method.

An alternative that doesn't require casting, but I think is worse since it is not as safe (regarding typing and potential issues that may be generated when not applied to correct sampler) is setting the property like `s.sampler.setProperty("HTTPSampler.proxyHost", "...")` or `s.sampler.setProperty(HTTPSamplerBase.PROXYHOST, "...")`

**Comment by rabelenda** [comment]
Closing this since we haven't had any news. Please let us know of any further comments or re open if you feel is still needed for review.
