### ISSUE TITLE
Functionally Defined Request Properties

### ISSUE THREAD

**Issue by MrThreepwood** [abstracta/jmeter-java-dsl#8]
I'd love to make the request building a little more functional to allow the generation of url/headers/body per request through code. We would love to use our model factories that we already have in our code base in order to performance test our endpoints.

I have a branch where I have implemented this for bodies:
https://github.com/abstracta/jmeter-java-dsl/compare/master...MrThreepwood:FunctionalRequest

I'd be happy to continue building out this pattern for the other properties in the builder if this is something you would want to accept. If it's not, we can work around this by creating our own DslHttpSampler. Currently the DslHttpSampler uses a lot of private variables, so even if you didn't want this functionality in the code base it would be helpful for people looking to extend its functionality to have protected functions that are used instead (getBody(), getHeaders() etc).

**Comment by rabelenda** [comment]
I really like the idea of being able to functionally define the body, or a way to define a pre processor. Pre processors are more powerful since they allow you to modify any property of a sampler, and you don't need to add a functional alternative for each property.

I guess you already have identified this, but the solution you have in that branch doesn't work, since the evaluation of the supplier happens even before the test plan starts executing (is not evaluated for each request). As a workaround for the time being you might consider creating a JSR223PreProcessor component, and from that pre processor call the method that builds the body. Something like this:

```java
httpSampler("myUrl")
  .body("${REQUEST_BODY}")
  .children(jsr223PreProcessor("import my.package.MyClass; vars["REQUEST_BODY"] = MyClass.buildBody()")
```

I know this solution is not ideal, since script used by pre processor is not typesafe and you don't have auto complete, but is an option. Another way would be implementing a custom JMeter PreProcessor which can receive an object as property, but that would highly probably have problems with serialization and the like, it may be something to explore, but is also quite more complex.

Provided example is considering that building bodies is stateless. If you need a stateful behavior (eg: incrementing a counter, iterating a list, etc) you can store in a variable (and get from it) the instance of the class that holds the state. If you need for the state to be shared between threads there are many alternatives. There is a built in component in jmeter which is usually used for the stateful behavior controlled through a csv file: [CSV Data Set config](https://jmeter.apache.org/usermanual/component_reference.html#CSV_Data_Set_Config).

I like the idea of making the components more easily extensible, I will take it into consideration for a future release.

**Comment by MrThreepwood** [comment]
Hmm, the preprocessor might work well enough. It's certainly not ideal to have to write our code as strings but it's not the end of the world, especially if it's that simple to call static functions in your code base.

I would definitely prefer to be able to compose a builder that is called for each request. Even if there was just some way to be given the class that is being modified. I'm not at all familiar with the way the preprocessors work, but I assume vars is a reference to a map on some object. I don't know how easy it would be, but if you could just do a 
```
preProcessor(processor: Function<RequestObject>)
```
That would cover all the bases for being able to modify the request but allow all the standard functionality you get from an IDE/Compiler with Java. Again, not sure if such a thing is reasonably doable from JMeter though. Would something as simple as 

```
.children(jsr223PreProcessor("import my.package.MyClass; vars.put('REQUEST_BODY', MyClass.modifyRequest(this))")
```
work? Not sure if you can pass this to the funciton from the script code. If you can it might be as simple as making a preProcessor function that takes the fully qualified name of a class that impliments an interface with a single function that takes whatever the type of "this" is in that context. Or I suppose the fully qualified name of a class with a static method with a specific signature?

**Comment by rabelenda** [comment]
I have merged the PR you sent and included the change in [latest release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.7)

**Comment by MrThreepwood** [comment]
Thanks. I might look into ways to make this look a little less strange/magical, but I don't know that it can be done without some fairly gross looking code. I may use it locally, but you may not want it in the project.

I'm thinking you'd likely have to accept a function to set the body, store that function somewhere in a statically accessible map with some generated key and then have a static function that proxies to the function in the map.

```
public void body(Supplier<String> supplier) {
    String id = UUID.randomUUID().toString();
    someStaticMap.put(id, supplier);
    body("${REQUEST_BODY}")
    addChild(jsr223PreProcessor("vars.put('REQUEST_BODY', fully.qualified.ClassName.bodyCaller(" + id + "))")
}
```

This would cause a memory leak of all the suppliers, so I'm thinking perhaps nest the map of suppliers in another map of String, Map<String, Supplier<String>> where the string is an id defined by the DslThreadGroup or test plan and is automatically cleared on completion.

**Comment by rabelenda** [comment]
Hello,

I have implemented support for using lambdas as pre & post processors scripts. Please, take a look at [latest release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.9) and use cases, and let me know what you think.

Regards

**Comment by MrThreepwood** [comment]
That looks awesome, thanks!
