### ISSUE TITLE
jmx2dsl extension guide

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#81]
There is no transpanent info about it. I want to know, is there some limitation around dsl implemenatation or it based on jmeter libs... etc.

**Comment by rabelenda** [comment]
Or are you asking for extending jmx2dsl for DSL classes that are not in jmeter-java-dsl lib? Like custom dsl test elements, or other dsl modules?

In such cases we haven't added documentation about such cases yet. 

If you have some custom DSL class, you can implement a CodeBuilder for it and then use DslCodeGenerator class (implementing another main that uses it [as jmx2dsl does](https://github.com/abstracta/jmeter-java-dsl/blob/master/jmeter-java-dsl-jmx2dsl/src/main/java/us/abstracta/jmeter/javadsl/jmx2dsl/Jmx2Dsl.java)) which is the core of jmx2dsl logic and register on it the associated DSL builder methods class. Check [DslCodeGenerator javadoc](https://github.com/abstracta/jmeter-java-dsl/blob/master/jmeter-java-dsl/src/main/java/us/abstracta/jmeter/javadsl/codegeneration/DslCodeGenerator.java).

Please let us know of you particular case, like what particular part of jmx2dsl you need to extend, and maybe we can improve docs or provide good advice on that particular scenario.

**Comment by kirillyu** [comment]
Ok, and if the class is not implemented in dsl it will crash? Maybe we can change it to dummy, or something else?

**Comment by rabelenda** [comment]
Currently, if a test element is found without an associated DSL CodeBuilder, the conversion adds an `unsupported()` call to the DSL. If an element is supported, but some special property/config on it is not, currently the property is being ignored. 

We have plans in the future to use the wrapper module instead of `unsupported()`, so the DSL code, even though is not optimal in such scenarios (a conversion could look like `testElement(MySampler.class).prop("myProp", "myVal")`), is still functional.

About unsupported properties, we may also implement something in the future if this proves to be an issue for users (please report such issue if you find any).

In general, as we have detailed in the release and as we encourage in general for the DSL: any issue/improvement you found, please report it as issue, so we can prioritize it. We have a lot of things in the backlog, but want to focus only in the ones that make a difference for users.
