### ISSUE TITLE
I was trying to use the project and noticed lot of vulnerabilities, please consider fixing them.

### ISSUE THREAD

**Issue by sbusanelli** [abstracta/jmeter-java-dsl#94]
![image](https://user-images.githubusercontent.com/18707170/163637863-4d05f81d-67c4-498a-bcd4-5ce7356db0ef.png)

**Comment by rabelenda** [comment]
Hello, thank you for reporting this.

What tool did you use to generate the report, so we can further review the issues and determine in they actually imply a risk or not.

As a side note, as far as you test sites which you rely on (which in genera should be the target of your tests), you should not be concerned about potential vulnerabilities, since you are only using this library as client and the main way of injecting vulnerabilities on clients is through server interactions. Since jmeter does not act, in general (unless you use distributed mode), as server, you shouldn't be concerned in general about vulenarbilities that might be generated from clients when server applications (webapps) use such vulnerable libraries.

As an end note, listed dependencies are included by JMeter (and not by the DSL itself, they are transitive dependencies), so it might be complicated to upgrade all the dependencies to not vulnerable ones.

Thank you again, and please if you can let us know what tool did you use to generate the report, or share the report itself to review each issue.

**Comment by sbusanelli** [comment]
Thanks for the quick response. I was using snyk code to scan.

**Comment by rabelenda** [comment]
I am closing this since we fixed most of vulnerabilities in [release 0.52.1](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.52.1).

Please let us know if you find anything else.

Regards
