### ISSUE TITLE
httpDefaults not working for GraphQL

### ISSUE THREAD

**Issue by MaksSieve** [abstracta/jmeter-java-dsl#97]
env: 

- jmeter-java-dsl:0.52
- jmeter-java-dsl-graphql:0.52

Steps to reproduce:
```java
testPlan(
  httpDefaults()
    .protocol("https")
    .host("some-endpoint/graphql"),
  rpsThreadGroup()
    .maxThreads(10)
    .rampToAndHold(10.0, Duration.ofSeconds(10),Duration.ofSeconds(10))
    .children(
      graphqlSampler("test", "/", "query")
     ),
  jtlWriter("test" + Instant.now().toString().replace(":", "-") + "/report.jtl"),
).run()
```

result (in logs):
```csv
timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,IdleTime,Connect
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-1,text,false,,862,0,1,1,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-2,text,false,,862,0,2,2,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-1,text,false,,862,0,2,2,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-2,text,false,,862,0,2,2,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-1,text,false,,862,0,2,2,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-2,text,false,,862,0,2,2,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-1,text,false,,862,0,2,2,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-2,text,false,,862,0,2,2,null,0,0,0
0,0,,Non HTTP response code: java.net.MalformedURLException,Non HTTP response message: Illegal character found in host: '/',RPS Thread Group-ThreadStarter 1-1,text,false,,862,0,2,2,null,0,0,0
```
I consider this problem is caused by totally overwriting url on GraphqlSampler construction, which is not flexible.

**Comment by rabelenda** [comment]
In httpDefaults you are setting in host operation also a path: have you tried using path for that, and setting a null url in graphqlSampler (so path is solved from host, otherwise it overrides the path specified in httpDefaults).

Regards

**Comment by MaksSieve** [comment]
Sorry for long answer, suggested workaround is working.

But in my opinion its not user friendly, I need some time to make proposal for another DSL.

**Comment by MaksSieve** [comment]
I've mentioned as not friendly not the way to set httpDefaults, but the need to use null as parameters and brutal overwriting inside graphqlSampler :)

**Comment by rabelenda** [comment]
any ideas how to improve it?

we have chosen such api considering different tradeoffs among which are consistency and ease of use for most of the scenarios and only use some workaround or additional code in some corner cases.

take into consideration that in java we can't have these 4 apis:

```
graphqlSampler(String query)
graphqlSampler(String name, String query)
graphqlSampler(String url, String query)
graphqlSampler(String name, String url, String query)
```

since the 2nd and 3rd would collide, unless we use some type different from string in some of the parameters, which would make general usage more verbose since you would require some "new X(..)".

Another alternative would be not making url part of the parameters, and provide a .url method instead. This would require additional code in simple cases where you have just one sampler, or a few samplers, and would not enforce users to think about url which would be error prone, which in general we try to avoid by making api enforce good practices.

Finally, in your use case you may use a java variable instead of httpDefaults which would make code shorter:

```java
String url = "https://some-endpoint/graphql";

testPlan(
  rpsThreadGroup()
    .maxThreads(10)
    .rampToAndHold(10.0, Duration.ofSeconds(10),Duration.ofSeconds(10))
    .children(
      graphqlSampler("test", url, "query")
     ),
  jtlWriter("test" + Instant.now().toString().replace(":", "-") + "/report.jtl"),
).run()
```

Please, let us know your thoughts :)

**Comment by MaksSieve** [comment]
> Another alternative would be not making url part of the parameters, and provide a .url method instead. This would require additional code in simple cases where you have just one sampler, or a few samplers, and would not enforce users to think about url which would be error prone, which in general we try to avoid by making api enforce good practices.

It's a good point just before you need to configure two-three dozen of similar samplers which have identical endpoints but significantly different bodies and file with testplan becomes unreadable. We solve it by incapsulating requests and scenarios (as list of requests) in separate classes where I don't want to set a ton of identical url or pass identical parameters).

So, I think we take a brainstorm tomorrow to make some suggestions on this topic :)

**Comment by MaksSieve** [comment]
@kirillyu you are welcome to discussion )))

**Comment by kirillyu** [comment]
I also think that the method.the url may be a good solution. Then the default will be null, which does not need to be thought about separately. For rare requests whose url will be different from httpDefaults, a bit of code will be added, but this is not redundant. Not as redundant as writing null in each of them.

But of course you need to understand the necessary set of APIs, if there are no conflicts, then you can implement the option without the url parameter.

**Comment by kirillyu** [comment]
But as far as I understand, we are not discussing the problem, but the implementation of the API component around this problem. The problem is that httpDefaults doesn't overwrite null? If yes, then this is bad, the whole logic of the httpDefaults build is based on checking for null.

**Comment by MaksSieve** [comment]
gentlemen, what resolution is for this issue?

**Comment by rabelenda** [comment]
Hello,

As far as I see it there is no bug with current implementation, only potential inconvenience when using httpDefautls with "full" url that requires setting null in url in graphqlSampler, instead of using a java variable or creating a custom method with the particularities of each user setting or config.

For the time being, unless this is a recurrent request by users, we will keep the url in graphqlSampler builder method as is, since we consider is the best way to make it explicit to users that a url is needed (either as parameter or as httpDefaults element) and avoid easy pitfall of missing specifying it. The alternative would require users always having to add an httpDefaults (which they have to know about, and is not as easy to learn/trace, and even error message from sampler migth be misleading) or invoking an "optional" url method, even for simple cases of just one sampler. Additionally, doing that would "lose" some consistency for httpSampler.

This is current decisions, but as every decision is subject to review and re evaluation.

Regards.
